# # This is a basic workflow to help you get started with Actions

name: ADempiere Publish

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  release:
    types: 
      - published
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: create dependences folder
      run: mkdir dependences
    - name: get adempiere source
      run: wget https://github.com/erpcya/adempiere/releases/download/3.9.3-rs-4.0/Adempiere_393LTS.tar.gz -c -O Adempiere.tar.gz
    - name: uncompress file
      run: tar -xzf Adempiere.tar.gz
    - name: move dependences
      run: mv Adempiere/lib/*.jar dependences/
    - name: move packages
      run: mv Adempiere/packages/*/lib/*.jar dependences/
    - name: Build with Gradle
      run: gradle createRelease
    - name: Epale
      run: pwd
    - name: Epale 1
      run: ls -la
    - name: Upload zip
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_ACCESS }}
      with:
        args: 'build/release/adempiere-gRPC-Server.zip.MD5'
